# This file is part of the EventBusJS library.
#
# Copyright (c) 2016-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Beñat Espiña <benatespina@gmail.com>
# @author Mikel Tuesta <mikeltuesta@gmail.com>

sudo: false

language: node_js

node_js:
  - 4
  - 5
  - 6

install:
    - npm install

script:
    - npm test

cache:
    directories:
        - node_modules
